apiVersion: "v1"
kind: "ServiceAccount"
metadata:
  namespace: "{{ .Release.Namespace }}"
  name: "{{ .Release.Name }}-{{ .Chart.Name }}-gateway"
  labels:
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.Version }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"

---
apiVersion: "v1"
kind: "ServiceAccount"
metadata:
  namespace: "{{ .Release.Namespace }}"
  name: "{{ .Release.Name }}-{{ .Chart.Name }}"
  {{ if .Values.sa_annotations -}}
  annotations:
    {{- range $k, $v := .Values.sa_annotations }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
  {{ end -}}
  labels:
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.Version }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"

---
apiVersion: "v1"
kind: "ServiceAccount"
metadata:
  namespace: "{{ .Release.Namespace }}"
  name: "{{ .Release.Name }}-{{ .Chart.Name }}-promtail"
  labels:
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.Version }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"

---
apiVersion: "rbac.authorization.k8s.io/v1"
kind: "ClusterRole"
metadata:
  name: "{{ .Release.Name }}-{{ .Chart.Name }}-promtail"
rules:
  - apiGroups: [""]
    resources:
      - "nodes"
      - "pods"
    verbs:
      - "get"
      - "list"
      - "watch"

---
apiVersion: "rbac.authorization.k8s.io/v1"
kind: "ClusterRoleBinding"
metadata:
  name: "{{ .Release.Name }}-{{ .Chart.Name }}-promtail"
roleRef:
  apiGroup: "rbac.authorization.k8s.io"
  kind: "ClusterRole"
  name: "{{ .Release.Name }}-{{ .Chart.Name }}-promtail"
subjects:
  - kind: "ServiceAccount"
    name: "{{ .Release.Name }}-{{ .Chart.Name }}-promtail"
    namespace: "{{ .Release.Namespace }}"
