piVersion: "v1"
kind: "ConfigMap"
metadata:
  namespace: "{{ .Release.Namespace }}"
  name: "{{ .Release.Name }}-{{ .Chart.Name }}"
  labels:
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.Version }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
data:
  loki.yaml: |
    auth_enabled: false

    server:
      http_listen_address: 0.0.0.0
      grpc_listen_address: 0.0.0.0
      http_listen_port: 3100
      grpc_listen_port: 9095
      log_level: "info"

    common:
      path_prefix: "/var/loki"
      replication_factor: {{ .Values.loki.replicas | default "2" }}

    memberlist:
      bind_addr: ["0.0.0.0"]
      bind_port: 7946
      join_members: ["{{ .Release.Name }}-{{ .Chart.Name }}-join.{{ .Release.Namespace }}.svc:7946"]

    schema_config:
      configs:
        - from: "2020-05-15"
          object_store: "s3"
          store: "boltdb-shipper"
          schema: "v12"
          index:
            prefix: "index_"
            period: "24h"

    storage_config:
      boltdb_shipper:
        shared_store: "s3"
        cache_ttl: "24h"
      aws:
        region: "{{ .Values.loki.aws_region }}"
        bucketnames: "{{ .Values.loki.aws_bucket }}"
        s3forcepathstyle: true
        sse_encryption: false
        insecure: false
      hedging:
        at: "250ms"
        up_to: 3
        max_per_second: 20

    limits_config:
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: "168h"
      ingestion_rate_mb: 10
      ingestion_burst_size_mb: 20
      max_concurrent_tail_requests: 20
      split_queries_by_interval: "15m"
      max_cache_freshness_per_query: "10m"

    query_range:
      align_queries_with_step: true

    compactor:
      shared_store: "s3"
      compaction_interval: "10m"

    ingester:
      max_transfer_retries: 0
      chunk_idle_period: "3m"
      chunk_retain_period: "1m"

    ruler:
      enable_alertmanager_v2: true
      alertmanager_url: "{{ .Values.loki.alertmanager }}"
      enable_api: true
      storage:
        type: "s3"
        s3:
          bucketnames: "{{ .Values.loki.aws_bucket }}"
          s3forcepathstyle: true
