apiVersion: "v1"
kind: "ConfigMap"
metadata:
  namespace: "{{ .Release.Namespace }}"
  name: "{{ .Release.Name }}-{{ .Chart.Name }}"
  labels:
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.Version }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
data:
  loki.yaml: |
    auth_enabled: false

    server:
      log_level: "info"
      http_listen_address: 0.0.0.0
      http_listen_port: 3100
      http_server_read_timeout: "300s"
      http_server_write_timeout: "300s"
      grpc_listen_address: 0.0.0.0
      grpc_listen_port: 9095
      # Limit on the size of a gRPC message this server can receive (bytes).
      grpc_server_max_recv_msg_size: 104857600
      # Limit on the size of a gRPC message this server can send (bytes).
      grpc_server_max_send_msg_size: 104857600

    common:
      path_prefix: "/var/loki"
      replication_factor: {{ .Values.loki.replicas | default "2" }}
      ring:
        kvstore:
          store: "memberlist"

    memberlist:
      bind_addr: ["0.0.0.0"]
      bind_port: 7946
      join_members: ["{{ .Release.Name }}-{{ .Chart.Name }}-join.{{ .Release.Namespace }}.svc:7946"]

    schema_config:
      configs:
        - from: "2020-05-15"
          object_store: "s3"
          store: "boltdb-shipper"
          schema: "v12"
          index:
            prefix: "index_"
            period: "24h"

    storage_config:
      boltdb_shipper:
        shared_store: "s3"
        cache_ttl: "24h"
      aws:
        bucketnames: "{{ .Values.loki.s3_bucket }}"
        sse_encryption: false
        {{ if .Values.loki.s3_is_aws -}}
        region: "{{ .Values.loki.aws_region }}"
        s3forcepathstyle: true
        insecure: false
        {{- else }}
        endpoint: "{{ .Values.loki.s3_endpoint }}"
        access_key_id: "{{ .Values.loki.s3_key_id }}"
        secret_access_key: "{{ .Values.loki.s3_key_secret }}"
        s3forcepathstyle: false
        insecure: true
        {{- end }}
      hedging:
        at: "250ms"
        up_to: 3
        max_per_second: 20

    limits_config:
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: "168h"
      ingestion_rate_mb: 20
      ingestion_burst_size_mb: 30
      split_queries_by_interval: "15m"
      max_cache_freshness_per_query: "10m"

    query_range:
      max_retries: 5
      align_queries_with_step: true
      cache_results: true
      results_cache:
        cache:
          enable_fifocache: true
          fifocache:
            size: 1024
            validity: "24h"

    frontend:
      compress_responses: true
      log_queries_longer_than: "10s"

    query_scheduler:
      # In-flight requests above this limit will fail with HTTP response status code 429
      # max_outstanding_requests_per_tenant: 300

    compactor:
      shared_store: "s3"
      compaction_interval: "10m"

    ingester:
      # The algorithm to use for compressing chunk. (none, gzip, lz4-64k, snappy, lz4-256k, lz4-1M, lz4, flate, zstd)
      chunk_encoding: "snappy"
      chunk_idle_period: "5m"
      chunk_retain_period: "1m"

    ingester_client:
      grpc_client_config:
        # gRPC client max receive message size (bytes).
        max_recv_msg_size: 104857600
        # gRPC client max send message size (bytes).
        max_send_msg_size: 104857600

    ruler:
      enable_alertmanager_v2: true
      alertmanager_url: "{{ .Values.loki.alertmanager }}"
      enable_api: true
      storage:
        type: "s3"
        s3:
          bucketnames: "{{ .Values.loki.s3_bucket }}"
          sse_encryption: false
          {{ if .Values.loki.s3_is_aws -}}
          s3forcepathstyle: true
          insecure: false
          {{ else -}}
          s3forcepathstyle: false
          insecure: true
          {{- end }}
