apiVersion: "v1"
kind: "Service"
metadata:
  namespace: "{{ .Release.Namespace }}"
  name: "{{ .Release.Name }}-{{ .Chart.Name }}-read"
  labels:
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.Version }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
spec:
  selector:
    app.kubernetes.io/name: "{{ .Release.Name }}-{{ .Chart.Name }}"
    app.kubernetes.io/role: "read"
  ports:
    - name: "http"
      port: 3100
      targetPort: 3100

---
apiVersion: "v1"
kind: "Service"
metadata:
  namespace: "{{ .Release.Namespace }}"
  name: "{{ .Release.Name }}-{{ .Chart.Name }}-write"
  labels:
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.Version }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
spec:
  selector:
    app.kubernetes.io/name: "{{ .Release.Name }}-{{ .Chart.Name }}"
    app.kubernetes.io/role: "write"
  ports:
    - name: "http"
      port: 3100
      targetPort: 3100

---
apiVersion: "v1"
kind: "Service"
metadata:
  namespace: "{{ .Release.Namespace }}"
  name: "{{ .Release.Name }}-{{ .Chart.Name }}-gw"
  labels:
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.Version }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
spec:
  selector:
    app.kubernetes.io/name: "{{ .Release.Name }}-{{ .Chart.Name }}-gateway"
  ports:
    - name: "http"
      port: 3100
      targetPort: 3100

---
apiVersion: "v1"
kind: "Service"
metadata:
  namespace: "{{ .Release.Namespace }}"
  name: "{{ .Release.Name }}-{{ .Chart.Name }}-join"
  labels:
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.Version }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
spec:
  selector:
    app.kubernetes.io/name: "{{ .Release.Name }}-{{ .Chart.Name }}"
  ports:
    - name: "join"
      port: 7946
      targetPort: 7946
