namespace_create: false

nginx:
  image: "nginx:1.25.1"
  # replicas: 1
  # request_cpu: "60m"
  # request_mem: "60m"
  # limit_cpu: "60Mi"
  # limit_mem: "60Mi"

loki:
  image: "grafana/loki:2.8.2"

promtail:
  image: "grafana/promtail:2.8.2"
