ns_create: false
sa_create: true
# sa_name: ""
# sa_annotations:
#   eks.amazonaws.com/role-arn: ""
#   eks.amazonaws.com/sts-regional-endpoints: "true"

nginx:
  image: "nginx:1.25.1"
  # replicas: 1
  # request_cpu: "100m"
  # request_mem: "64Mi"
  # limit_cpu: "100m"
  # limit_mem: "64Mi"

loki:
  image: "grafana/loki:2.8.2"
  replicas: 2
  s3_is_aws: false
  # aws_region: ""
  s3_endpoint: "minio.testing.svc:9000"
  s3_bucket: "loki-data"
  s3_key_id: "testing"
  s3_key_secret: "1qaz!QAZ"
  # alertmanager: ""
  reader_limit_cpu: "100m"
  reader_limit_mem: "250Mi"
  writer_limit_cpu: "100m"
  writer_limit_mem: "200Mi"

promtail:
  image: "grafana/promtail:2.8.2"
  # request_cpu: "100m"
  # request_mem: "165Mi"
  # limit_cpu: "100m"
  # limit_mem: "165Mi"
