ns_create: false
sa_create: true
# sa_name: ""
# sa_annotations:
#   eks.amazonaws.com/role-arn: ""
#   eks.amazonaws.com/sts-regional-endpoints: "true"

nginx:
  image: "nginx:1.25.1"
  # replicas: 1
  # request_cpu: "60m"
  # request_mem: "60m"
  # limit_cpu: "60Mi"
  # limit_mem: "60Mi"

loki:
  image: "grafana/loki:2.8.2"
  replicas: 2
  # aws_region: ""
  # s3_bucket: "loki-data"
  # s3_endpoint: "minio.testing.svc:9000"
  # alertmanager: ""
  # request_cpu: "100m"
  # request_mem: "100m"
  # limit_cpu: "160Mi"
  # limit_mem: "160Mi"

promtail:
  image: "grafana/promtail:2.8.2"
  # request_cpu: "100m"
  # request_mem: "100m"
  # limit_cpu: "160Mi"
  # limit_mem: "160Mi"
