namespace_create: false

nginx:
  image: "nginx:1.25.1"
  # replicas: 1
  # request_cpu: "60m"
  # request_mem: "60m"
  # limit_cpu: "60Mi"
  # limit_mem: "60Mi"

loki:
  image: "grafana/loki:2.8.2"
  replicas: 2
  aws_region: ""
  aws_bucket: ""
  alertmanager: ""
  # request_cpu: "100m"
  # request_mem: "100m"
  # limit_cpu: "160Mi"
  # limit_mem: "160Mi"

promtail:
  image: "grafana/promtail:2.8.2"
