ns_create: false
sa_create: true
# sa_name: ""
# sa_annotations:
#   eks.amazonaws.com/role-arn: ""
#   eks.amazonaws.com/sts-regional-endpoints: "true"

nginx:
  # https://hub.docker.com/r/nginxinc/nginx-unprivileged/tags
  image: "nginxinc/nginx-unprivileged:1.25.2"
  # replicas: 1
  # limit_cpu: "100m"
  # limit_mem: "64Mi"

loki:
  # https://hub.docker.com/r/grafana/loki/tags
  image: "grafana/loki:2.9.0"
  writer_replicas: 2
  reader_replicas: 2
  s3_is_aws: false
  # aws_region: ""
  s3_endpoint: "minio.testing.svc:9000"
  s3_bucket: "loki-data"
  s3_key_id: "testing"
  s3_key_secret: "1qaz!QAZ"
  # alertmanager: ""
  reader_limit_cpu: "100m"
  reader_limit_mem: "250Mi"
  writer_limit_cpu: "100m"
  writer_limit_mem: "200Mi"

promtail:
  # https://hub.docker.com/r/grafana/promtail/tags
  image: "grafana/promtail:2.9.0"
  # limit_cpu: "100m"
  # limit_mem: "165Mi"
