{{ if .Values.serviceAccount.create -}}
apiVersion: "v1"
kind: "ServiceAccount"
metadata:
  namespace: "{{ .Release.Namespace }}"
  {{ if .Values.serviceAccount.name -}}
  name: "{{ .Values.serviceAccount.name }}"
  {{ else -}}
  name: "{{ .Release.Name }}-{{ .Chart.Name }}"
  {{ end -}}
  labels:
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.Version }}"
  {{ with .Values.serviceAccount.annotations -}}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{ end -}}
{{ end -}}
