{{ if .Values.configMap.create -}}
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  namespace: "{{ .Release.Namespace }}"
  name: "{{ .Release.Name }}-{{ .Chart.Name }}-config"
  labels:
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.Version }}"
data:
  {{ .Values.configMap.fileName }}: |
  {{ .Values.configMap.data | indent 2 }}
{{ end -}}
