{{ if .Values.configMap.create -}}
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  namespace: "{{ .Release.Namespace }}"
  name: "{{ .Values.configMap.name }}"
  labels:
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.Version }}"
data:
  {{ .Values.configMap.configName }}: |-
    {{- with .Values.configMap.configData }}
    {{- toString . | nindent 4 }}
    {{ end -}}
{{ end -}}
