{{ if .Values.ingress.create -}}
apiVersion: "networking.k8s.io/v1"
kind: "Ingress"
metadata:
  namespace: "{{ .Release.Namespace }}"
  {{ if .Values.ingress.name -}}
  name: "{{ .Values.ingress.name }}"
  {{ else -}}
  name: "{{ .Release.Name }}-{{ .Chart.Name }}"
  {{ end -}}
  labels:
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.Version }}"
  {{ with .Values.ingress.annotations -}}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: "{{ .Values.ingress.ingressClass }}"
  {{ with .Values.ingress.tls -}}
  tls:
    {{- toYaml . | nindent 4 }}
  {{ end -}}
  rules:
  {{- with .Values.ingress.rules }}
    {{- toYaml . | nindent 4 }}
  {{ end -}}
{{ end -}}
