{{ if .Values.monitoring.enabled -}}
apiVersion: "monitoring.coreos.com/v1"
kind: "PodMonitor"
metadata:
  namespace: "{{ .Release.Namespace }}"
  name: "{{ .Release.Name }}-{{ .Chart.Name }}"
  labels:
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.Version }}"
    {{- with .Values.monitoring.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ .Release.Name }}-{{ .Chart.Name }}"
  podMetricsEndpoints:
  {{- with .Values.monitoring.endpoints }}
    {{- toYaml . | nindent 4 }}
  {{ end -}}
{{ end -}}
