{{ if .Values.namespace.create -}}
apiVersion: "v1"
kind: "Namespace"
metadata:
  name: "{{ .Release.Namespace }}"
  {{- with .Values.namespace.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{ end -}}
{{ end -}}
