{{ if .Values.service.create -}}
apiVersion: "v1"
kind: "Service"
metadata:
  namespace: "{{ .Release.Namespace }}"
  {{ if .Values.service.name -}}
  name: "{{ .Values.service.name }}"
  {{ else -}}
  name: "{{ .Release.Name }}-{{ .Chart.Name }}"
  {{ end -}}
  labels:
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.Version }}"
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    app.kubernetes.io/name: "{{ .Release.Name }}-{{ .Chart.Name }}"
  ports:
  {{- with .Values.service.ports }}
    {{- toYaml . | nindent 4 }}
  {{ end -}}
{{ end -}}
