namespace:
  create: false
  labels: {}

serviceAccount:
  create: true
  name: ""
  annotations: {}

configMap:
  create: false
  name: ""
  configName: ""
  configData: ""

deploy:
  replicas: 1
  strategy: "Recreate"
  volumes: []
  containers:
    - name: "app"
      image: "nginx:latest"
      imagePullPolicy: "IfNotPresent"
      ports:
        - name: "http"
          protocol: "TCP"
          containerPort: 80
  initContainers: {}
  podAnnotations: {}
  securityContext: {}
  nodeSelector:
    kubernetes.io/os: "linux"
  tolerations: []
  affinity: {}

service:
  create: true
  labels: {}
  ports:
    - name: "http"
      port: 80
      protocol: "TCP"
      targetPort: "http"

monitoring:
  enabled: false
  labels:
    release: "prom-operator"
  endpoints:
    - port: "http"
      interval: "30s"
      honorLabels: true
