namespace:
  create: false
  labels: {}

serviceAccount:
  create: true
  name: ""
  annotations: {}

configMap:
  create: false
  name: ""
  configName: ""
  configData: ""

deploy:
  replicas: 1
  strategy: "Recreate"
  securityContext:
    create: false

containers:
  image: "nginx:latest"
  resources:
    create: false

service:
  create: true
  port: 80
