namespace:
  create: false
  labels: {}

serviceAccount:
  create: true
  name: ""
  annotations: {}

configMap:
  create: false
  name: ""
  configName: ""
  configData: ""

deploy:
  replicas: 1
  strategy: "Recreate"
  volumes: []
  containers: []
  podAnnotations: {}
  securityContext: {}

containers:
  image: "nginx:latest"
  resources:
    create: false

service:
  create: true
  labels: {}
  ports:
    - name: "http"
      port: 80
      protocol: "TCP"
      targetPort: "http"

monitoring:
  enabled: true
  labels:
    release: "prom-operator"
  endpoints:
    - port: "http"
      interval: "30s"
      honorLabels: true
